name: CI/CD for Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: game_bot
          POSTGRES_USER: raul
          POSTGRES_PASSWORD: raul333
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U raul" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python3.10 python3.10-dev python3-pip
          python3.10 --version
          python3.10 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3.10 -m pip install -r requirements.txt || { echo "Failed to install dependencies"; exit 1; }
        

      # ###tests
      # - name: Run Tests
      #   run: |
      #     pytest -v || { echo "Tests failed"; exit 1; }

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: raulramazanov
          password: raul333777999

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: raulramazanov/game_bot:latest
